### ISSUE TITLE
error when creating keys

### ISSUE THREAD

**Issue by rt4mn** [rukykf/btcpay#3]
Thanks for making this extension!

I am running CiviCRM 5.37.0. on wordpress Version 5.7.1 on a debian 10 vps. 

When I attempt to create keys in the API Explorer V3, I get an error which says 

`    {

    "is_error": 1,
    "error_message": "The GMP or BCMATH extension for PHP is required."
}`

After seeing that error, I accessed the vps hosting wordpress and installed both of those extensions using apt install php-bcmath php-gmp, but the error persists.

**Comment by rukykf** [comment]
hello thanks for trying the extension! 

I'll get to work investigating this issue. I never actually tested this extension with Wordpress.... I only ever tried it with Drupal after creating it. But I'll look into it and follow up as soon as possible.

**Comment by rt4mn** [comment]
I think I fixed it, just needed to restart apache after installing the modules. 

Huge thank you again for making this extension! Now we can finally accept payments in crypto and have them automatically count towards our overall fundraising goal.

**Comment by rukykf** [comment]
Awesome!!!
